### ISSUE TITLE
Produkt bearbeiten: Fallback-Sprache CSS-Bug

### ISSUE THREAD

**Issue by hagenschulze** [isotope/core#1492]
Moin Moin,

Im Backend beim Editieren von Produkten ist oben im Versions-Panel das Feld für das Sprachen-Fallback nicht klickbar:
![bug_1](https://cloud.githubusercontent.com/assets/13450260/8823702/559079e2-306f-11e5-8c29-a2813e4934c5.png)

Beim Anlegen eines neuen Produkts gibt es ebenfalls einen kosmetischen floating Fehler:
![bug_2](https://cloud.githubusercontent.com/assets/13450260/8823738/8e17c216-306f-11e5-8402-268bf68c4fa0.png)

Mein Workaround sieht folgendermaßen aus: 
```css
.tl_version_panel:after {
    content: ' '; 
    display: block; 
    clear: both;
}

.tl_version_panel #tl_language {
    position: relative;
    z-index: 2;
}
```

Besser wäre natürlich DC_ProductData.php entsprechend anzupassen.
