### ISSUE TITLE
Fix responsive images definitions when loaded from database

### ISSUE THREAD

**Issue by contaoacademy** [isotope/core#2420]
Currently, the pixel densities of the images are correctly used for the gallery. 

However, there is no 100% support for all features from Contao.
For example, images are not converted to webp.
Also, the lazy attribute is not added in the source code

![screen-20230216_IYiy5I4j](https://user-images.githubusercontent.com/23719181/219324523-c4bd8013-944b-4d5a-80fd-013a7b6e7f42.jpg)

![screen-20230216_xWEmmxjD](https://user-images.githubusercontent.com/23719181/219324534-40733ca9-5f7c-4860-8ad3-425dd0febe8b.jpg)

**Comment by fritzmg** [comment]
I can't confirm the issue. Format conversion works as expected.

**Comment by fritzmg** [comment]
I can confirm that this issue occurs if you use an image size from the database 👍

When using an image size from the bundle config it works.

**Comment by rburch** [comment]
I'm not sure what you mean by use image size from the database vs bundle config but conversion and lazy don't work for me either.

**Comment by fritzmg** [comment]
In Contao you can define responsive image sizes via the database - i.e. via the back end in your theme - or via the `contao/core-bundle` bundle configuration under `contao.image.sizes`.

**Comment by rburch** [comment]
I'm configuring it in the Contao Image Theme settings. So that must be pulling from the database once configured.

**Comment by contaoacademy** [comment]
You could do the following in config.yml.
Example:
```
# config/config.yaml
contao:
  image:
    sizes:
      shop-main-image:
        width: 300
        height: 300
        resize_mode: crop
        zoom: 100
        css_class: configyml
        lazy_loading: true
        densities: 1.5x, 2x
        formats:
          jpg: [ webp, jpg ]
          png: [ webp, png ]
```
